name: "Download Metabase Release Jar"
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  download_metabase_jar:
    runs-on: ubuntu-latest
    steps:
      - name: Download File To Workspace
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://download.sys.truenas.net/TrueNAS-SCALE-Cobia/23.10.0.1/TrueNAS-SCALE-23.10.0.1.iso
          file-name: TrueNAS-SCALE-23.10.0.1.iso
          location: .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: TrueNAS-SCALE-23.10.0.1.iso

          
