name: "Download Metabase Release Jar"
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  download_metabase_jar:
    runs-on: ubuntu-latest
    steps:
      - name: Download File To Workspace
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://downloads.metabase.com/v0.39.4/metabase.jar
          file-name: metabase.jar
          location: .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          # Note-worthy description of changes in release
          # body: # optional
          # Path to load note-worthy description of changes in release from
          # body_path: # optional
          # Gives the release a custom name. Defaults to tag name
          # name: # optional
          # Creates a draft release. Defaults to false
          # draft: # optional
          # Identify the release as a prerelease. Defaults to false
          # prerelease: # optional
          # Newline-delimited list of path globs for asset files to upload
          files: metabase.jar
          
