name: "Download Metabase Release Jar"
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  download_metabase_jar:
    runs-on: ubuntu-latest
    steps:
      - name: Download File To Workspace
        uses: carlosperate/download-file-action@v2.0.1
        with:
          file-url: https://cdn.zabbix.com/zabbix/binaries/stable/6.0/6.0.25/zabbix_agent2-6.0.25-windows-amd64-openssl.msi
          file-name: zabbix_agent2-6.0.25-windows-amd64-openssl.msi
          location: .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: zabbix_agent2-6.0.25-windows-amd64-openssl.msi

          
