name: "Download Metabase Release Jar"
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  download_metabase_jar:
    runs-on: ubuntu-latest
    steps:
      - name: Download File To Workspace
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://download.nextcloud.com/server/releases/nextcloud-24.0.1.tar.bz2
          file-name: nextcloud-24.0.1.tar.bz2
          location: .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: nextcloud-24.0.1.tar.bz2

          
