name: "Download Metabase Release Jar"
on: [push]
jobs:
  download_metabase_jar:
    runs-on: ubuntu-latest
    steps:
      - name: Download File To Workspace
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://downloads.metabase.com/v0.39.4/metabase.jar
          file-name: metabase-0.39.4.jar
          location: .
      - name: upload Jar to Release
        uses: actions/upload-artifact@v2.2.3
        with:
          name: metabase
          path: ./*.jar
          
